from __future__ import annotations

from typing import Protocol


class OrchestratorBackend(Protocol):
    def start(self, prompt: str) -> None: ...
    def resume(self, prompt: str) -> None: ...
    def follow_up(self, text: str) -> None: ...
    def abort(self) -> None: ...
    def wait_idle(self) -> None: ...
