server {
  listen 80;
  location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html;
  }
  location /api/ai/ {
    proxy_pass http://sale-agent:8000/api/ai/;
  }
  location /api/ {
    proxy_pass http://business-mock:8080/api/;
  }
}
